# Generated by Django 5.0.6 on 2024-08-20 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.TimeField()),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'ap_Alert',
                'verbose_name_plural': 'ap_Alerts',
                'db_table': 'ap_Alert',
            },
        ),
        migrations.CreateModel(
            name='AuthRole',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'ap_AuthRole',
                'verbose_name_plural': 'ap_AuthRoles',
                'db_table': 'ap_AuthRole',
            },
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'ap_Block',
                'verbose_name_plural': 'ap_Blocks',
                'db_table': 'ap_Block',
            },
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
            ],
            options={
                'verbose_name': 'ap_Plant',
                'verbose_name_plural': 'ap_Plants',
                'db_table': 'ap_Plant',
            },
        ),
        migrations.CreateModel(
            name='SensorTagType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('units', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'ap_SensorTagType',
                'verbose_name_plural': 'ap_SensorTagTypes',
                'db_table': 'ap_SensorTagType',
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.authrole')),
            ],
            options={
                'verbose_name': 'ap_AuthUser',
                'verbose_name_plural': 'ap_AuthUsers',
                'db_table': 'ap_AuthUser',
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('open', models.BooleanField(default=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.alert')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.block')),
            ],
            options={
                'verbose_name': 'ap_Incident',
                'verbose_name_plural': 'ap_Incidents',
                'db_table': 'ap_Incident',
            },
        ),
        migrations.CreateModel(
            name='IncidentTransaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('msg', models.TextField(blank=True, null=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.incident')),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.authuser')),
            ],
            options={
                'verbose_name': 'ap_IncidentTransaction',
                'verbose_name_plural': 'ap_IncidentTransactions',
                'db_table': 'ap_IncidentTransaction',
            },
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.block')),
            ],
            options={
                'verbose_name': 'ap_Line',
                'verbose_name_plural': 'ap_Lines',
                'db_table': 'ap_Line',
            },
        ),
        migrations.AddField(
            model_name='incident',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.line'),
        ),
        migrations.AddField(
            model_name='alert',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.line'),
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('height_px', models.IntegerField()),
                ('width_px', models.IntegerField()),
                ('x_coordinate', models.IntegerField()),
                ('y_coordinate', models.IntegerField()),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.line')),
            ],
            options={
                'verbose_name': 'ap_Machine',
                'verbose_name_plural': 'ap_Machines',
                'db_table': 'ap_Machine',
            },
        ),
        migrations.AddField(
            model_name='block',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.plant'),
        ),
        migrations.CreateModel(
            name='SensorTag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('min_val', models.FloatField()),
                ('max_val', models.FloatField()),
                ('nominal_val', models.FloatField(blank=True, null=True)),
                ('threshold_alert', models.CharField(max_length=100)),
                ('continuous_record', models.BooleanField(default=False)),
                ('frequency', models.CharField(blank=True, max_length=100, null=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.machine')),
                ('tag_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.sensortagtype')),
            ],
            options={
                'verbose_name': 'ap_SensorTag',
                'verbose_name_plural': 'ap_SensorTags',
                'db_table': 'ap_SensorTag',
            },
        ),
        migrations.AddField(
            model_name='incident',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.sensortag'),
        ),
        migrations.CreateModel(
            name='DaqLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('value', models.FloatField()),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.sensortag')),
            ],
            options={
                'verbose_name': 'ap_DaqLog',
                'verbose_name_plural': 'ap_DaqLogs',
                'db_table': 'ap_DaqLog',
            },
        ),
        migrations.AddField(
            model_name='alert',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.sensortag'),
        ),
    ]
