# Generated by Django 5.0.6 on 2024-07-09 06:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionLine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('inactive', models.BooleanField(default=False)),
                ('modified', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'ap_ProductionLine',
                'verbose_name_plural': 'ap_ProductionLines',
                'db_table': 'ap_ProductionLine',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('units', models.CharField(max_length=50)),
                ('min_val', models.IntegerField()),
                ('max_val', models.IntegerField()),
                ('inactive', models.BooleanField(default=False)),
                ('modified', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'ap_Tag',
                'verbose_name_plural': 'ap_Tags',
                'db_table': 'ap_Tag',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('value', models.IntegerField()),
                ('inactive', models.BooleanField(default=False)),
                ('modified', models.CharField(max_length=255)),
                ('line', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.productionline')),
                ('tag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.tag')),
            ],
            options={
                'verbose_name': 'ap_Log',
                'verbose_name_plural': 'ap_Logs',
                'db_table': 'ap_Log',
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('report_title', models.CharField(max_length=255)),
                ('report_type', models.CharField(max_length=255)),
                ('report_category', models.CharField(max_length=255)),
                ('report_sub_cat', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('incident_dtls', models.CharField(max_length=1000)),
                ('issued', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('inactive', models.BooleanField(default=False)),
                ('modified', models.CharField(max_length=255)),
                ('line', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.productionline')),
                ('tag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.tag')),
            ],
            options={
                'verbose_name': 'ap_Alert',
                'verbose_name_plural': 'ap_Alerts',
                'db_table': 'ap_Alert',
            },
        ),
    ]
