# Generated by Django 5.0.6 on 2024-07-09 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='incident_dtls',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='issued',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='report_category',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='report_sub_cat',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='report_title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='report_type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='role',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='productionline',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
