# Generated by Django 5.0.6 on 2024-07-18 14:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_alert_incident_dtls_alter_alert_issued_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='alert',
            name='resolve_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='severity',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='alert',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
